### ISSUE TITLE
Script crashes

### ISSUE THREAD

**Issue by abukaj** [ziemowit-s/covid-poland-by-region#1]
It crashes like that:
```
$ python main.py 
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    from covid_stats import CovidStats
  File "/home/abukaj/covid_poland/covid_stats.py", line 2, in <module>
    import robobrowser
  File "/home/abukaj/anaconda3/envs/covid/lib/python3.8/site-packages/robobrowser/__init__.py", line 3, in <module>
    from .browser import RoboBrowser
  File "/home/abukaj/anaconda3/envs/covid/lib/python3.8/site-packages/robobrowser/browser.py", line 8, in <module>
    from werkzeug import cached_property
ImportError: cannot import name 'cached_property' from 'werkzeug' (/home/abukaj/anaconda3/envs/covid/lib/python3.8/site-packages/werkzeug/__init__.py)
```

I have installed it like that:
```
$ pip install -r requirements.txt 
Collecting matplotlib
  Downloading matplotlib-3.2.1-cp38-cp38-manylinux1_x86_64.whl (12.4 MB)
     |████████████████████████████████| 12.4 MB 371 kB/s 
Collecting numpy
  Downloading numpy-1.18.4-cp38-cp38-manylinux1_x86_64.whl (20.7 MB)
     |████████████████████████████████| 20.7 MB 981 kB/s 
Collecting pandas
  Downloading pandas-1.0.3-cp38-cp38-manylinux1_x86_64.whl (10.0 MB)
     |████████████████████████████████| 10.0 MB 1.0 MB/s 
Collecting mplcursors
  Downloading mplcursors-0.3-py3-none-any.whl (18 kB)
Collecting robobrowser
  Downloading robobrowser-0.5.3.tar.gz (22 kB)
Collecting kiwisolver>=1.0.1
  Downloading kiwisolver-1.2.0-cp38-cp38-manylinux1_x86_64.whl (92 kB)
     |████████████████████████████████| 92 kB 46 kB/s 
Collecting cycler>=0.10
  Downloading cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1
  Downloading pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
     |████████████████████████████████| 67 kB 670 kB/s 
Collecting python-dateutil>=2.1
  Downloading python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
     |████████████████████████████████| 227 kB 788 kB/s 
Collecting pytz>=2017.2
  Downloading pytz-2020.1-py2.py3-none-any.whl (510 kB)
     |████████████████████████████████| 510 kB 706 kB/s 
Collecting beautifulsoup4>=4.3.2
  Downloading beautifulsoup4-4.9.1-py3-none-any.whl (115 kB)
     |████████████████████████████████| 115 kB 784 kB/s 
Collecting requests>=2.6.0
  Downloading requests-2.23.0-py2.py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 566 kB/s 
Collecting six>=1.9.0
  Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting Werkzeug>=0.10.4
  Downloading Werkzeug-1.0.1-py2.py3-none-any.whl (298 kB)
     |████████████████████████████████| 298 kB 396 kB/s 
Collecting soupsieve>1.2
  Downloading soupsieve-2.0.1-py3-none-any.whl (32 kB)
Collecting chardet<4,>=3.0.2
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
     |████████████████████████████████| 133 kB 709 kB/s 
Requirement already satisfied: certifi>=2017.4.17 in /home/abukaj/anaconda3/envs/covid/lib/python3.8/site-packages (from requests>=2.6.0->robobrowser->-r requirements.txt (line 5)) (2020.4.5.1)
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Downloading urllib3-1.25.9-py2.py3-none-any.whl (126 kB)
     |████████████████████████████████| 126 kB 804 kB/s 
Collecting idna<3,>=2.5
  Downloading idna-2.9-py2.py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 683 kB/s 
Building wheels for collected packages: robobrowser
  Building wheel for robobrowser (setup.py) ... done
  Created wheel for robobrowser: filename=robobrowser-0.5.3-py3-none-any.whl size=16419 sha256=d70eb9f1f2c120430263c96231ccc04b93e3e90e9a68046c88150d8c49a9272e
  Stored in directory: /home/abukaj/.cache/pip/wheels/29/f5/46/15be591132a6321c7c4f02e7c6c54efdc016b847f5642143f2
Successfully built robobrowser
Installing collected packages: kiwisolver, six, cycler, pyparsing, python-dateutil, numpy, matplotlib, pytz, pandas, mplcursors, soupsieve, beautifulsoup4, chardet, urllib3, idna, requests, Werkzeug, robobrowser
Successfully installed Werkzeug-1.0.1 beautifulsoup4-4.9.1 chardet-3.0.4 cycler-0.10.0 idna-2.9 kiwisolver-1.2.0 matplotlib-3.2.1 mplcursors-0.3 numpy-1.18.4 pandas-1.0.3 pyparsing-2.4.7 python-dateutil-2.8.1 pytz-2020.1 requests-2.23.0 robobrowser-0.5.3 six-1.15.0 soupsieve-2.0.1 urllib3-1.25.9
```

And the conda env has been built like that:
```
$ conda create -n covid
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.8.2
  latest version: 4.8.3

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /home/abukaj/anaconda3/envs/covid



Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate covid
#
# To deactivate an active environment, use
#
#     $ conda deactivate

$ conda activate covid
$ conda install pip
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.8.2
  latest version: 4.8.3

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /home/abukaj/anaconda3/envs/covid

  added / updated specs:
    - pip


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    python-3.8.3               |       hcff3b4d_0        49.1 MB
    setuptools-46.4.0          |           py38_0         515 KB
    ------------------------------------------------------------
                                           Total:        49.6 MB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main
  ca-certificates    pkgs/main/linux-64::ca-certificates-2020.1.1-0
  certifi            pkgs/main/linux-64::certifi-2020.4.5.1-py38_0
  ld_impl_linux-64   pkgs/main/linux-64::ld_impl_linux-64-2.33.1-h53a641e_7
  libedit            pkgs/main/linux-64::libedit-3.1.20181209-hc058e9b_0
  libffi             pkgs/main/linux-64::libffi-3.3-he6710b0_1
  libgcc-ng          pkgs/main/linux-64::libgcc-ng-9.1.0-hdf63c60_0
  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-9.1.0-hdf63c60_0
  ncurses            pkgs/main/linux-64::ncurses-6.2-he6710b0_1
  openssl            pkgs/main/linux-64::openssl-1.1.1g-h7b6447c_0
  pip                pkgs/main/linux-64::pip-20.0.2-py38_3
  python             pkgs/main/linux-64::python-3.8.3-hcff3b4d_0
  readline           pkgs/main/linux-64::readline-8.0-h7b6447c_0
  setuptools         pkgs/main/linux-64::setuptools-46.4.0-py38_0
  sqlite             pkgs/main/linux-64::sqlite-3.31.1-h62c20be_1
  tk                 pkgs/main/linux-64::tk-8.6.8-hbc83047_0
  wheel              pkgs/main/linux-64::wheel-0.34.2-py38_0
  xz                 pkgs/main/linux-64::xz-5.2.5-h7b6447c_0
  zlib               pkgs/main/linux-64::zlib-1.2.11-h7b6447c_3


Proceed ([y]/n)? y


Downloading and Extracting Packages
python-3.8.3         | 49.1 MB   | #################################################################################################################################################################################################################################### | 100% 
setuptools-46.4.0    | 515 KB    | #################################################################################################################################################################################################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```

**Comment by ziemowit-s** [comment]
robobrowser library, through Flask lib - have a problem with werkzeug>0.16.0.

see StackOverflow: 
https://stackoverflow.com/questions/46457179/python3-cannot-import-name-cached-property

Since you installed Werkzeug-1.0.1 - it cause the problem. 

In `covid_stats.py`, before robobrowser import I put:
```
import werkzeug
werkzeug.cached_property = werkzeug.utils.cached_property
```
which solved the problem. 

Alternativelly you can  downgrade werkzeug to 0.16.0:
`pip install -U werkzeug==0.16.0`
